### ISSUE TITLE
RoadMap version 2.0

### ISSUE THREAD

**Issue by aristath** [shoestrap/shoestrap-3#122]
- [ ] re-organize the settings on the customizer in more meaningful sections
- [ ] Add js so that the preview is live on the customizer
- [ ] Add the customizer options to the backend
